image: Visual Studio 2022

environment:
  PYTHON: "C:\\Python312-x64"

build_script:
  - "C:\\Python312-x64\\python.exe -m pip install pandas openpyxl pyinstaller"
  - "C:\\Python312-x64\\python.exe -m PyInstaller --onefile --name 長照金額計算程式 --hidden-import openpyxl.cell._writer process.py"

artifacts:
  - path: dist\長照金額計算程式.exe
    name: 長照金額計算程式
