image: Visual Studio 2022

environment:
  PYTHON: "C:\\Python312-x64"

build_script:
  - "C:\\Python312-x64\\python.exe -m pip install pandas openpyxl pyinstaller"
  - "C:\\Python312-x64\\python.exe -m PyInstaller --onefile --name LTC_Calculator --hidden-import openpyxl.cell._writer process.py"

artifacts:
  - path: dist\LTC_Calculator.exe
    name: LTC_Calculator
